### PR TITLE
Fix: fixed the bug that can not request to NSEIndia server

### PR DESCRIPTION
**Pull request by karmamaster**
1. Updated the code to make it get all cookie from new base URL.

### CODE REVIEW

**Comment by asrafalih** [comment]
Am reviewing this PR.

**Comment by karmamaster** [comment]
> Am reviewing this PR.

Is it working with you?

**Comment by asrafalih** [comment]
> > Am reviewing this PR.
> 
> Is it working with you?

No, It's not working. API timed out.

**Comment by karmamaster** [comment]
@asrafalih really? Peoples are using my fork with the same code base and they confirmed on issue page. This really weird, can you provide screenshot of the issue so I can recheck it?

**Comment by karmamaster** [comment]
As this git master seems don't have enough time to work on this so I will add more features on my fork. If anyone need help on this please create issue on my forked module. 

Thank you.

**Pull request closed without merging**
